// Generated by gencpp from file RcsROSMsg/Box.msg
// DO NOT EDIT!


#ifndef RCSROSMSG_MESSAGE_BOX_H
#define RCSROSMSG_MESSAGE_BOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RcsROSMsg
{
template <class ContainerAllocator>
struct Box_
{
  typedef Box_<ContainerAllocator> Type;

  Box_()
    : center()
    , orientation()
    , extents()
    , color()  {
    }
  Box_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , orientation(_alloc)
    , extents(_alloc)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _center_type;
  _center_type center;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _orientation_type;
  _orientation_type orientation;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _extents_type;
  _extents_type extents;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _color_type;
  _color_type color;




  typedef boost::shared_ptr< ::RcsROSMsg::Box_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RcsROSMsg::Box_<ContainerAllocator> const> ConstPtr;

}; // struct Box_

typedef ::RcsROSMsg::Box_<std::allocator<void> > Box;

typedef boost::shared_ptr< ::RcsROSMsg::Box > BoxPtr;
typedef boost::shared_ptr< ::RcsROSMsg::Box const> BoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RcsROSMsg::Box_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RcsROSMsg::Box_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RcsROSMsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'RcsROSMsg': ['/home/smanschi/catkin_ws/src/RcsROSMsg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RcsROSMsg::Box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RcsROSMsg::Box_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RcsROSMsg::Box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RcsROSMsg::Box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RcsROSMsg::Box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RcsROSMsg::Box_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RcsROSMsg::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d449619cc8365cdca7896d853c652e3";
  }

  static const char* value(const ::RcsROSMsg::Box_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d449619cc8365cdULL;
  static const uint64_t static_value2 = 0xca7896d853c652e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::RcsROSMsg::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RcsROSMsg/Box";
  }

  static const char* value(const ::RcsROSMsg::Box_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RcsROSMsg::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] center\n\
float64[] orientation\n\
float64[] extents\n\
uint8[] color\n\
";
  }

  static const char* value(const ::RcsROSMsg::Box_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RcsROSMsg::Box_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.orientation);
      stream.next(m.extents);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Box_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RcsROSMsg::Box_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RcsROSMsg::Box_<ContainerAllocator>& v)
  {
    s << indent << "center[]" << std::endl;
    for (size_t i = 0; i < v.center.size(); ++i)
    {
      s << indent << "  center[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.center[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "extents[]" << std::endl;
    for (size_t i = 0; i < v.extents.size(); ++i)
    {
      s << indent << "  extents[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.extents[i]);
    }
    s << indent << "color[]" << std::endl;
    for (size_t i = 0; i < v.color.size(); ++i)
    {
      s << indent << "  color[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.color[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCSROSMSG_MESSAGE_BOX_H
