// Generated by gencpp from file RcsROSMsg/BoxArray.msg
// DO NOT EDIT!


#ifndef RCSROSMSG_MESSAGE_BOXARRAY_H
#define RCSROSMSG_MESSAGE_BOXARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <RcsROSMsg/Box.h>

namespace RcsROSMsg
{
template <class ContainerAllocator>
struct BoxArray_
{
  typedef BoxArray_<ContainerAllocator> Type;

  BoxArray_()
    : boxVec()  {
    }
  BoxArray_(const ContainerAllocator& _alloc)
    : boxVec(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::RcsROSMsg::Box_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::RcsROSMsg::Box_<ContainerAllocator> >::other >  _boxVec_type;
  _boxVec_type boxVec;




  typedef boost::shared_ptr< ::RcsROSMsg::BoxArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RcsROSMsg::BoxArray_<ContainerAllocator> const> ConstPtr;

}; // struct BoxArray_

typedef ::RcsROSMsg::BoxArray_<std::allocator<void> > BoxArray;

typedef boost::shared_ptr< ::RcsROSMsg::BoxArray > BoxArrayPtr;
typedef boost::shared_ptr< ::RcsROSMsg::BoxArray const> BoxArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RcsROSMsg::BoxArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RcsROSMsg::BoxArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RcsROSMsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'RcsROSMsg': ['/home/smanschi/catkin_ws/src/RcsROSMsg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RcsROSMsg::BoxArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RcsROSMsg::BoxArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RcsROSMsg::BoxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RcsROSMsg::BoxArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RcsROSMsg::BoxArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RcsROSMsg::BoxArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RcsROSMsg::BoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9862fba05703964b9b065069bee8eba4";
  }

  static const char* value(const ::RcsROSMsg::BoxArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9862fba05703964bULL;
  static const uint64_t static_value2 = 0x9b065069bee8eba4ULL;
};

template<class ContainerAllocator>
struct DataType< ::RcsROSMsg::BoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RcsROSMsg/BoxArray";
  }

  static const char* value(const ::RcsROSMsg::BoxArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RcsROSMsg::BoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Box[] boxVec\n\
\n\
================================================================================\n\
MSG: RcsROSMsg/Box\n\
float64[] center\n\
float64[] orientation\n\
float64[] extents\n\
uint8[] color\n\
";
  }

  static const char* value(const ::RcsROSMsg::BoxArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RcsROSMsg::BoxArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.boxVec);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoxArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RcsROSMsg::BoxArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RcsROSMsg::BoxArray_<ContainerAllocator>& v)
  {
    s << indent << "boxVec[]" << std::endl;
    for (size_t i = 0; i < v.boxVec.size(); ++i)
    {
      s << indent << "  boxVec[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::RcsROSMsg::Box_<ContainerAllocator> >::stream(s, indent + "    ", v.boxVec[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCSROSMSG_MESSAGE_BOXARRAY_H
